/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TunerKits (https://sketchfab.com/tunerkits)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/toyota-supra-a90-3d-printeble-model-e43ee16157e4475ab486bc00e3db3949
title: Toyota Supra A90 (3d printeble model)
*/
import './test8.css'
import React, { useRef, useState, useEffect } from "react";
import { useGLTF, useAnimations, } from "@react-three/drei";
import { useSnapshot } from 'valtio'
import { state } from './store'

export const Model = (props) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/model/test/supra_glb/scene.glb");
    const { actions, names } = useAnimations(animations, group);

    const snap = useSnapshot(state)

    useEffect(() => {
        if (snap.anime) {
            actions[names].reset().fadeIn(0.5).play()
        } else {
            actions[names].reset().fadeIn(0.5).stop()
        }
    }, [actions, names, snap.anime]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model">
                    <group
                        name="bd535709a1ec44a6a1cf183dac01ecbafbx"
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="vihlop"
                                    position={[0, 55.08, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="vihlop_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["vihlop_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="bagajnik"
                                    position={[-37.15, 117.6, 99.5]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <group name="steklo_zadnee" position={[37.45, -2.69, 2.93]}>
                                        <mesh
                                            name="steklo_zadnee_Material_#550_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["steklo_zadnee_Material_#550_0"].geometry}
                                            material={materials.Material_550_2}
                                        />
                                    </group>
                                    <mesh
                                        name="bagajnik_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["bagajnik_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="bagajnik_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["bagajnik_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="bagajnik_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["bagajnik_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="steklo_lobovoye"
                                    position={[0, 88.37, 24.51]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="steklo_lobovoye_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["steklo_lobovoye_Material_#550_0"].geometry}
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="krisha"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="krisha_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["krisha_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.7}
                                        />
                                    </mesh>
                                    <mesh
                                        name="krisha_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["krisha_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="kapot"
                                    position={[-45.92, 84.11, -39.54]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="kapot_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["kapot_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="kapot_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["kapot_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="osnova_01"
                                    position={[-0.03, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="osnova_01_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["osnova_01_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="osnova_01_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["osnova_01_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="osnova_03"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="osnova_03_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["osnova_03_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="osnova_03_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["osnova_03_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="osnova_02"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="osnova_02_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["osnova_02_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="Rectangle002"
                                    position={[-0.03, 19.49, -137.96]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Rectangle002_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Rectangle002_Material_#550_0"].geometry}
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="Dvornik_01"
                                    position={[58.67, 69.7, -65.73]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Dvornik_01_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Dvornik_01_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="Dvornik_02"
                                    position={[58.67, 69.7, -65.73]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Dvornik_02_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Dvornik_02_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="Object004"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Object004_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object004_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Object004_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object004_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Object004_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object004_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Object004_Material_#550_0_3"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object004_Material_#550_0_3"].geometry}
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="Object006"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Object006_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object006_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Object006_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object006_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Object006_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object006_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Box001"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Box001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box001_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Box001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box001_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Box001_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box001_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Object008"
                                    position={[0, 89.27, 23.37]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Object008_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object008_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Object008_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object008_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="stupitsa_pered_levaya"
                                    position={[-57.63, 11.63, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stupitsa_pered_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["stupitsa_pered_levaya_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="stupitsa_pered_levaya_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["stupitsa_pered_levaya_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="fara_steklo_pered_levaya"
                                    position={[0, 89.27, -216.1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_steklo_pered_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_steklo_pered_levaya_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="fara_steklo_zad_levaya"
                                    position={[0, 65.69, 185.17]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_steklo_zad_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_steklo_zad_levaya_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="fortochka_levaya"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fortochka_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fortochka_levaya_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="Krilo_levoye"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Krilo_levoye_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Krilo_levoye_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Krilo_levoye_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Krilo_levoye_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="fara_zad_levaya"
                                    position={[0, 65.69, 108.48]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_zad_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["fara_zad_levaya_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="fara_zad_levaya_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_zad_levaya_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="stoyka_levaya"
                                    position={[-0.03, 90.54, -80.21]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stoyka_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["stoyka_levaya_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="dver_levaya"
                                    position={[-88.91, 70.23, -41.43]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <group name="steklo_levoye" position={[88.91, -65.4, 19.04]}>
                                        <group
                                            name="zerkalo_levoye"
                                            position={[-87.02, 39.88, 3.61]}
                                        >
                                            <mesh
                                                name="zerkalo_levoye_Material_#550_0"
                                                castShadow
                                                receiveShadow
                                                geometry={
                                                    nodes["zerkalo_levoye_Material_#550_0"].geometry
                                                }
                                                material={materials.Material_550_1}
                                            />
                                        </group>
                                        <mesh
                                            name="steklo_levoye_Material_#550_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["steklo_levoye_Material_#550_0"].geometry}
                                            material={materials.Material_550_2}
                                        />
                                    </group>
                                    <mesh
                                        name="dver_levaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["dver_levaya_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="dver_levaya_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["dver_levaya_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="dver_levaya_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["dver_levaya_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="tormoznoy_disk_zad"
                                    position={[-78.99, 32.76, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="tormoznoy_disk_zad_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["tormoznoy_disk_zad_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="stupitsa_zad"
                                    position={[-77.76, 29.62, 110.73]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stupitsa_zad_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["stupitsa_zad_Material_#550_0"].geometry}
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="pakrishka_01"
                                    position={[-80.68, 58.54, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="pakrishka_01_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["pakrishka_01_Material_#550_0"].geometry}
                                        material={materials.Material_550_4}
                                    />
                                </group>
                                <group
                                    name="Disk_01"
                                    position={[-93.79, 32.76, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Disk_01_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_01_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Disk_01_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_01_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Box002"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Box002_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box002_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Box002_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box002_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Box002_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box002_Material_#550_0_2"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Disk_004"
                                    position={[93.79, 32.76, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Disk_004_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_004_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Disk_004_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_004_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Krilo_levoye001"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Krilo_levoye001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Krilo_levoye001_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="Krilo_levoye001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Krilo_levoye001_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                
                                <group
                                    name="Object009"
                                    position={[0, 89.27, 23.37]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Object009_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object009_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Object009_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Object009_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Rulevou_kulak_leviy001"
                                    position={[70.63, 22.96, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Rulevou_kulak_leviy001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="Rulevou_kulak_leviy001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy001_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="Rulevou_kulak_leviy001_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy001_Material_#550_0_2"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="dver_levaya001"
                                    position={[88.91, 70.23, -41.43]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <group
                                        name="steklo_levoye001"
                                        position={[-88.91, -65.4, 19.04]}
                                    >
                                        <mesh
                                            name="steklo_levoye001_Material_#550_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                                nodes["steklo_levoye001_Material_#550_0"].geometry
                                            }
                                            material={materials.Material_550_2}
                                        />
                                    </group>
                                    <group
                                        name="zerkalo_levoye001"
                                        position={[-1.89, -25.53, 22.65]}
                                    >
                                        <mesh
                                            name="zerkalo_levoye001_Material_#550_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                                nodes["zerkalo_levoye001_Material_#550_0"].geometry
                                            }
                                            material={materials.Material_550_1}
                                        />
                                    </group>
                                    <mesh
                                        name="dver_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["dver_levaya001_Material_#550_0"].geometry}
                                        material={materials.Material_550_0}
                                    >
                                        <meshStandardMaterial
                                            color={snap.color}
                                            roughness={0}
                                            metalness={0.9}
                                        />
                                    </mesh>
                                    <mesh
                                        name="dver_levaya001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["dver_levaya001_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="dver_levaya001_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["dver_levaya001_Material_#550_0_2"].geometry
                                        }
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="fara_steklo_pered_levaya001"
                                    position={[0, 89.27, -216.1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_steklo_pered_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_steklo_pered_levaya001_Material_#550_0"]
                                                .geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="fara_steklo_zad_levaya001"
                                    position={[0, 65.69, 185.17]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_steklo_zad_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_steklo_zad_levaya001_Material_#550_0"]
                                                .geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="fara_zad_levaya001"
                                    position={[0, 65.69, 108.48]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_zad_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_zad_levaya001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="fara_zad_levaya001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_zad_levaya001_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="fortochka_levaya001"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fortochka_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fortochka_levaya001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="pakrishka_004"
                                    position={[80.68, 58.54, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="pakrishka_004_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["pakrishka_004_Material_#550_0"].geometry}
                                        material={materials.Material_550_4}
                                    />
                                </group>
                                <group
                                    name="stoyka_levaya001"
                                    position={[0.03, 90.54, -80.21]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stoyka_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["stoyka_levaya001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="stupitsa_pered_levaya001"
                                    position={[57.63, 11.63, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stupitsa_pered_levaya001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["stupitsa_pered_levaya001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="stupitsa_pered_levaya001_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["stupitsa_pered_levaya001_Material_#550_0_1"]
                                                .geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="stupitsa_zad001"
                                    position={[77.76, 29.62, 110.73]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="stupitsa_zad001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["stupitsa_zad001_Material_#550_0"].geometry}
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="tormoznoy_disk_zad001"
                                    position={[78.99, 32.76, 123.34]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="tormoznoy_disk_zad001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["tormoznoy_disk_zad001_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="tormoznoy_disk_����������001"
                                    position={[78.99, 32.76, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="tormoznoy_disk_����������001_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["tormoznoy_disk_����������001_Material_#550_0"]
                                                .geometry
                                        }
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="pakrishka_003"
                                    position={[80.68, 58.54, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="pakrishka_003_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["pakrishka_003_Material_#550_0"].geometry}
                                        material={materials.Material_550_4}
                                    />
                                </group>
                                <group
                                    name="Disk_003"
                                    position={[93.79, 32.76, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Disk_003_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_003_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Disk_003_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_003_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="pakrishka_002"
                                    position={[-80.68, 58.54, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="pakrishka_002_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["pakrishka_002_Material_#550_0"].geometry}
                                        material={materials.Material_550_4}
                                    />
                                </group>
                                <group
                                    name="tormoznoy_disk_����������"
                                    position={[-78.99, 32.76, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="tormoznoy_disk_����������_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["tormoznoy_disk_����������_Material_#550_0"]
                                                .geometry
                                        }
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Rulevou_kulak_leviy"
                                    position={[-70.63, 22.96, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Rulevou_kulak_leviy_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy_Material_#550_0"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="Rulevou_kulak_leviy_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy_Material_#550_0_1"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="Rulevou_kulak_leviy_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["Rulevou_kulak_leviy_Material_#550_0_2"].geometry
                                        }
                                        material={materials.Material_550_3}
                                    />
                                </group>
                                <group
                                    name="Disk_002"
                                    position={[-93.79, 32.76, -123.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="Disk_002_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_002_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Disk_002_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Disk_002_Material_#550_0_1"].geometry}
                                        material={materials.Material_550}
                                    />
                                </group>
                                <group
                                    name="Box005"
                                    position={[-2.89, 22.76, 44.83]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <group name="Object_158" position={[14.53, 48.68, 10.58]}>
                                        <mesh
                                            name="Box005_Material_#550_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["Box005_Material_#550_0"].geometry}
                                            material={materials.Material_550}
                                        />
                                        <mesh
                                            name="Box005_Material_#550_0_1"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["Box005_Material_#550_0_1"].geometry}
                                            material={materials.Material_550_3}
                                        />
                                        <mesh
                                            name="Box005_Material_#550_0_2"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["Box005_Material_#550_0_2"].geometry}
                                            material={materials.Material_550_1}
                                        />
                                        <mesh
                                            name="Box005_Material_#550_0_3"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes["Box005_Material_#550_0_3"].geometry}
                                            material={materials.Material_550_5}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="motorniy_shit"
                                    position={[0, 89.27, 23.98]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="motorniy_shit_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["motorniy_shit_Material_#550_0"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="motorniy_shit_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["motorniy_shit_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                </group>
                                <group
                                    name="fara_steklo_pered_pravaya"
                                    position={[0, 89.27, -216.1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                >
                                    <mesh
                                        name="fara_steklo_pered_pravaya_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                            nodes["fara_steklo_pered_pravaya_Material_#550_0"]
                                                .geometry
                                        }
                                        material={materials.Material_550_2}
                                    />
                                </group>
                                <group
                                    name="Box003"
                                    position={[0, 61.56, -93.99]}
                                    rotation={[0, -1.57, 0]}
                                >
                                    <mesh
                                        name="Box003_Material_#550_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box003_Material_#550_0"].geometry}
                                        material={materials.Material_550}
                                    />
                                    <mesh
                                        name="Box003_Material_#550_0_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box003_Material_#550_0_1"].geometry}
                                        material={materials.Material_550_3}
                                    />
                                    <mesh
                                        name="Box003_Material_#550_0_2"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box003_Material_#550_0_2"].geometry}
                                        material={materials.Material_550_1}
                                    />
                                    <mesh
                                        name="Box003_Material_#550_0_3"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes["Box003_Material_#550_0_3"].geometry}
                                        material={materials.Material_550_5}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group >
    );
}

useGLTF.preload("/model/test/supra_glb/scene.glb");
